apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.credentials.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.credentials.password | quote }}
  POSTGRES_DB: {{ .Values.credentials.db | quote }}
  DATABASE_URL: "postgresql://{{ .Values.credentials.user }}:{{ .Values.credentials.password }}@postgres:5432/{{ .Values.credentials.db }}"
